add roothide

diff --git a/scripts/palera1n_menu b/scripts/palera1n_menu
--- a/scripts/palera1n_menu
+++ b/scripts/palera1n_menu
@@ -71,6 +71,53 @@ while true; do
       ;;
   esac
 done
+elif [ "$jbtype" = "RootHide" ]; then
+while true; do
+  CHOICE="$(whiptail --nocancel --title "palera1n | use arrow keys" --menu \
+    "
+  Jailbreak Type: $jbtype
+  Arguments: $args" $whiptail_height $whiptail_width 8 \
+    '1' 'Start' \
+    '2' 'Options' \
+    '3' 'Switch' \
+    '4' 'Exit' 3>&1 1>&2 2>&3)"
+  case "$CHOICE" in
+    1)
+      clear
+      echo ''
+      echo "# == INFORMATION =="
+      echo "# ${YELLOW}- If you encounter lockdownd errors make sure to${NORMAL}"
+      echo "# ${YELLOW}unlock your device and replug.${NORMAL}"
+      echo "# ${YELLOW}- arm64e is not supported!${NORMAL}"
+      echo "# ${YELLOW}- You may encounter issues with AMD cpus.${NORMAL}"
+      echo "# ===== DEBUG ====="
+      echo "# Chosen Jailbreak Type: ${BLUE}$jbtype${NORMAL}"
+      echo "# Chosen Flags: ${BLUE}$args${NORMAL}"
+      echo ''
+      /usr/bin/palera1n $args
+      sleep 2
+      echo ''
+      echo "# ===== DEBUG ====="
+      echo "# Chosen Jailbreak Type: ${BLUE}$jbtype${NORMAL}"
+      echo "# Chosen Flags: ${BLUE}$args${NORMAL}"
+      echo ''
+      enter_to_quit
+      /usr/bin/palera1n_menu
+      ;;
+    2)
+      clear
+      /usr/bin/palera1n_options
+      ;;
+    3)
+      clear
+       /usr/bin/palera1n_switch
+       ;;
+     4)
+      clear
+      /usr/bin/palen1x_menu
+      ;;
+  esac
+done
 elif [ "$jbtype" = "Rootful" ]; then
 while true; do
   CHOICE="$(whiptail --nocancel --title "palera1n | use arrow keys" --menu \
@@ -93,13 +140,13 @@ while true; do
       echo "# ${YELLOW}- arm64e is not supported!${NORMAL}"
       echo "# == DEBUG =="
       echo "# Chosen Jailbreak Type: ${BLUE}$jbtype${NORMAL}"
-      echo "# Chosen Flags: -f ${BLUE}$args${NORMAL}"
-      /usr/bin/palera1n -f $args
+      echo "# Chosen Flags: ${BLUE}$args${NORMAL}"
+      /usr/bin/palera1n $args
       sleep 2
       echo ''
       echo "# == DEBUG =="
       echo "# Chosen Jailbreak Type: ${BLUE}$jbtype${NORMAL}"
-      echo "# Chosen Flags: -f ${BLUE}$args${NORMAL}"
+      echo "# Chosen Flags: ${BLUE}$args${NORMAL}"
       echo ''
       enter_to_quit
       /usr/bin/palera1n_menu
